name: Node.js CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
 
    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4
 
    # Step 2: Set up the Node.js environment with caching
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
 
    # Step 3: Install dependencies (Playwright and others)
    - run: npm install
      working-directory: playwright-testing
 
    # Step 4: Install Playwright browsers (if you're using Playwright)
    - name: Install Playwright Browsers
      run: npx playwright install
      working-directory: playwright-testing
 
    # Step 5: Run the tests inside the playwright-testing directory
    - run: npm test
      working-directory: playwright-testing
